To the swift result
facile-it/FunctionalKit pull request #28
Opened 2019-07-22 14:55 UTC by AndreaRR18

Replaced our enum with the system one. 
Fix all the stencil with new Swift Result.

@ChrisMyrants @broomburgo Please review.

2019-07-22 16:32 UTC, ChrisMyrants approved these changes
@AndreaRR18 done, good job

2019-07-23 13:17 UTC, broomburgo requested changes

2019-07-23 13:17 UTC, broomburgo commented on Sources/FunctionalKit/Result.swift
> +    public typealias RightType = Success
`LeftType` and `RightType` should be inverted.

2019-07-23 13:17 UTC, broomburgo commented on Sources/FunctionalKit/Result.swift
> +    typealias Generic<F,A> = Result<A,F> where F: Error
`Generic` type parameters should have the same order as `Result` ones.

2019-07-23 13:17 UTC, broomburgo commented on Sources/FunctionalKit/Result.swift
> +    public func run() throws -> Success {
This is redundant now. Swift `Result` already includes a `get()` method that does the same thing.

2019-07-26 12:42 UTC, broomburgo approved these changes

2019-07-26 12:43 UTC, merged